### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jsina** [bcbee/react-navigation-bug-3956#1]
Hey, I've found this project form [#issuecomment-381173148](https://github.com/react-navigation/react-navigation/issues/3956#issuecomment-381173148) , I wanna know what do you exactly do for solving the problem?

**Comment by dbztech-fastlane** [comment]
I’m not exactly sure what the actual fix is (still looking), but someone over in the react navigation thread that spawned this suggested adding this in your App.js to suppress the warning:
‘import { YellowBox } from 'react-native';
YellowBox.ignoreWarnings(['Warning: isMounted(...) is deprecated', 'Module RCTImageLoader']);’

**Comment by bcbee** [comment]
I’m not exactly sure what the actual fix is (still looking), but someone over in the react navigation thread that spawned this suggested adding this in your App.js to suppress the warning:
`import { YellowBox } from 'react-native';
YellowBox.ignoreWarnings(['Warning: isMounted(...) is deprecated', 'Module RCTImageLoader']);`

**Comment by gauravagam** [comment]
I got the same issue but it got fixed after adding headerMode:'none' to stacknavigator.
`const AppNavigator = StackNavigator({
    Home: { screen: AllComponents },
    List: { screen: ListComponent },
  },
  {
    initialRouteName: 'Home',
    headerMode:'none',
  }
)`

**Comment by nalorim** [comment]
Is the problem related to header while passing params between components? that's why it causes memory leaks?
